// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function trigger(currentTime, gainNode) {
  var attackTime = currentTime.contextTime + 0.3;
  var gainParam = gainNode.gain;
  gainParam.cancelScheduledValues(currentTime.contextTime);
  gainParam.setTargetAtTime(0.99, currentTime.contextTime + 0.001, 0.3 / 3.0);
  gainParam.setTargetAtTime(0.5, attackTime, 0.7 / 3.0);
  return /* () */0;
}

function endTrigger(currentTime, gainNode) {
  var gainParam = gainNode.gain;
  gainParam.cancelScheduledValues(currentTime.contextTime);
  gainParam.setTargetAtTime(0.0005, currentTime.contextTime, 1.2 / 3.0);
  return /* () */0;
}

var attack = 0.3;

var decay = 0.7;

var sustain = 0.5;

var release = 1.2;

exports.attack = attack;
exports.decay = decay;
exports.sustain = sustain;
exports.release = release;
exports.trigger = trigger;
exports.endTrigger = endTrigger;
/* No side effect */
