// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function trigger(currentTime, gainNode) {
  var attackTime = currentTime.contextTime + 2.0;
  var gainParam = gainNode.gain;
  gainParam.cancelScheduledValues(currentTime.contextTime);
  gainParam.setTargetAtTime(0.99, currentTime.contextTime + 0.001, 2.0 / 3.0);
  gainParam.setTargetAtTime(0.3, attackTime, 2.0 / 3.0);
  return /* () */0;
}

function endTrigger(currentTime, gainNode) {
  var gainParam = gainNode.gain;
  gainParam.cancelScheduledValues(currentTime.contextTime);
  gainParam.setTargetAtTime(0.0005, currentTime.contextTime, 1.5 / 3.0);
  return /* () */0;
}

var attack = 2.0;

var decay = 2.0;

var sustain = 0.3;

var release = 1.5;

exports.attack = attack;
exports.decay = decay;
exports.sustain = sustain;
exports.release = release;
exports.trigger = trigger;
exports.endTrigger = endTrigger;
/* No side effect */
