// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Pervasives from "bs-platform/lib/es6/pervasives.js";

function trigger(envelope) {
  var match = envelope.envelopeParams;
  var attack = match.attack;
  var decay = match.decay;
  var sustain = match.sustain;
  var targetValue = match.targetValue;
  var currentTime = envelope.audioContext.getOutputTimestamp();
  var attackTime = currentTime.contextTime + attack;
  envelope.targetParam.cancelScheduledValues(currentTime.contextTime);
  envelope.targetParam.setTargetAtTime(targetValue, currentTime.contextTime + Pervasives.epsilon_float, attack / 3.0);
  envelope.targetParam.setTargetAtTime(sustain * targetValue, attackTime, decay / 3.0);
  return /* () */0;
}

function endTrigger(envelope) {
  var match = envelope.envelopeParams;
  var release = match.release;
  var currentTime = envelope.audioContext.getOutputTimestamp();
  envelope.targetParam.cancelScheduledValues(currentTime.contextTime);
  envelope.targetParam.setTargetAtTime(Pervasives.epsilon_float, currentTime.contextTime, release / 3.0);
  return /* () */0;
}

function update(param, envelope) {
  var envelopeParams = envelope.envelopeParams;
  switch (param.tag | 0) {
    case /* Attack */0 :
        envelopeParams.attack = param[0];
        return /* () */0;
    case /* Decay */1 :
        envelopeParams.decay = param[0];
        return /* () */0;
    case /* Sustain */2 :
        envelopeParams.sustain = param[0];
        return /* () */0;
    case /* Release */3 :
        envelopeParams.release = param[0];
        return /* () */0;
    case /* TargetValue */4 :
        envelopeParams.targetValue = param[0];
        return /* () */0;
    
  }
}

function make($staropt$star, targetParam, audioCtx) {
  var targetValue = $staropt$star !== undefined ? $staropt$star : 1.0;
  targetParam.value = Pervasives.epsilon_float;
  var envelopeParams = {
    attack: 0.2,
    decay: 0.3,
    sustain: 0.1,
    release: 1.0,
    targetValue: targetValue
  };
  return {
          envelopeParams: envelopeParams,
          targetParam: targetParam,
          audioContext: audioCtx
        };
}

var defaultAttack = 0.2;

var defaultDecay = 0.3;

var defaultSustain = 0.1;

var defaultRelease = 1.0;

export {
  defaultAttack ,
  defaultDecay ,
  defaultSustain ,
  defaultRelease ,
  trigger ,
  endTrigger ,
  update ,
  make ,
  
}
/* No side effect */
