// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AudioNode$WebAudio from "./AudioNode.bs.js";

function setType(filterNode, filterType) {
  switch (filterType) {
    case /* Lowpass */0 :
        filterNode.type = "lowpass";
        return /* () */0;
    case /* Highpass */1 :
        filterNode.type = "highpass";
        return /* () */0;
    case /* Bandpass */2 :
        filterNode.type = "bandpass";
        return /* () */0;
    case /* Lowshelf */3 :
    case /* Highself */4 :
    case /* Peaking */5 :
    case /* Notch */6 :
    case /* Allpass */7 :
        console.log("Filter type not implemented yet");
        return /* () */0;
    
  }
}

AudioNode$WebAudio.Impl({ });

export {
  setType ,
  
}
/*  Not a pure module */
