// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as AudioNode$WebAudio from "./AudioNode.bs.js";

function Imp(T) {
  return { };
}

AudioNode$WebAudio.Impl({ });

export {
  Imp ,
  
}
/*  Not a pure module */
