// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var AudioNode$WebAudio = require("./AudioNode.bs.js");

function Imp(T) {
  return { };
}

AudioNode$WebAudio.Impl({ });

exports.Imp = Imp;
/*  Not a pure module */
