// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var AudioNode$WebAudio = require("./AudioNode.bs.js");

function Impl(T) {
  return { };
}

AudioNode$WebAudio.Impl({ });

function setOscillatorNodeType(oscillatorType, oscillatorNode) {
  if (oscillatorType.tag) {
    oscillatorNode.setPeriodicWave(oscillatorType[0]);
  } else {
    oscillatorNode.type = oscillatorType[0];
  }
  return oscillatorNode;
}

exports.Impl = Impl;
exports.setOscillatorNodeType = setOscillatorNodeType;
/*  Not a pure module */
