// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var AudioNode$WebAudio = require("./AudioNode.bs.js");

function Impl(T) {
  return { };
}

AudioNode$WebAudio.Impl({ });

exports.Impl = Impl;
/*  Not a pure module */
