// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var FFT$WebAudio = require("../FFT/FFT.bs.js");

function toTypedArray(floatArray) {
  var realCoefficients = new Float32Array($$Array.map((function (x) {
              return x.re;
            }), floatArray));
  var imaginaryCoefficients = new Float32Array($$Array.map((function (x) {
              return x.im;
            }), floatArray));
  return /* tuple */[
          realCoefficients,
          imaginaryCoefficients
        ];
}

function calculateCoefficients(samples) {
  return toTypedArray(FFT$WebAudio.fft($$Array.map((function (value) {
                        return {
                                re: value,
                                im: 0.0
                              };
                      }), samples)));
}

exports.toTypedArray = toTypedArray;
exports.calculateCoefficients = calculateCoefficients;
/* No side effect */
