// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Oscillator$WebAudio from "../Oscillator/Oscillator.bs.js";

function make(audioCtx) {
  var paramOscillator = audioCtx.createGain();
  paramOscillator.gain.value = 0.5;
  var lfoOscillator = Oscillator$WebAudio.make(/* Sine */0, audioCtx);
  lfoOscillator.oscillatorNode.frequency.value = 3.0;
  Oscillator$WebAudio.start(lfoOscillator);
  var constantSourceNode = audioCtx.createConstantSource();
  Oscillator$WebAudio.connect(paramOscillator, lfoOscillator);
  constantSourceNode.connect(paramOscillator);
  var lfoGain = audioCtx.createGain();
  paramOscillator.connect(lfoGain.gain);
  return {
          lfoOscillator: lfoOscillator,
          lfoGain: lfoGain,
          audioContext: audioCtx
        };
}

function connect(target, lfo) {
  lfo.lfoGain.connect(target);
  return lfo;
}

function setFrequency(frequency, lfo) {
  Oscillator$WebAudio.setFrequency(frequency, lfo.lfoOscillator);
  return lfo;
}

var defaultFrequency = 3.0;

export {
  defaultFrequency ,
  make ,
  connect ,
  setFrequency ,
  
}
/* Oscillator-WebAudio Not a pure module */
