// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Oscillator$WebAudio from "../Oscillator/Oscillator.bs.js";

function make(audioCtx) {
  var paramOscillator = audioCtx.createGain();
  paramOscillator.gain.value = 0.5;
  var oscillator = Oscillator$WebAudio.make(/* Sine */0, audioCtx);
  oscillator.oscillatorNode.frequency.value = 3.0;
  Oscillator$WebAudio.start(oscillator);
  var constantSourceNode = audioCtx.createConstantSource();
  Oscillator$WebAudio.connect(paramOscillator, oscillator);
  constantSourceNode.connect(paramOscillator);
  var lfo = audioCtx.createGain();
  paramOscillator.connect(lfo.gain);
  return {
          oscillator: oscillator,
          lfo: lfo
        };
}

function connect(target, lfo) {
  lfo.lfo.connect(target);
  return /* () */0;
}

function setFrequency(frequency, lfo) {
  return Oscillator$WebAudio.setFrequency(frequency, lfo.oscillator);
}

var defaultFrequency = 3.0;

export {
  defaultFrequency ,
  make ,
  connect ,
  setFrequency ,
  
}
/* Oscillator-WebAudio Not a pure module */
