// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

var appContext = React.createContext({
      audioContext: undefined,
      triggerTargets: /* [] */0,
      addToTriggerTargets: (function (param) {
          return /* () */0;
        }),
      removeFromTriggerTargets: (function (param) {
          return /* () */0;
        })
    });

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = appContext.Provider;

export {
  appContext ,
  makeProps ,
  make ,
  
}
/* appContext Not a pure module */
