// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";
import * as Knob$WebAudio from "./Knob.bs.js";
import * as Envelope$WebAudio from "../Envelope/Envelope.bs.js";

function EnvelopeUnit(Props) {
  var envelope = Props.envelope;
  return React.createElement("div", {
              className: "unit-container"
            }, React.createElement("div", undefined, React.createElement(Knob$WebAudio.make, {
                      name: "ATTACK",
                      config: {
                        minValue: Pervasives.epsilon_float,
                        maxValue: 2.0,
                        scale: /* Linear */0,
                        size: 50
                      },
                      initialParamValue: envelope.envelopeParams.attack,
                      setParamValue: (function (value) {
                          return Envelope$WebAudio.update({
                                      TAG: /* Attack */0,
                                      _0: value
                                    }, envelope);
                        })
                    }), React.createElement(Knob$WebAudio.make, {
                      name: "DECAY",
                      config: {
                        minValue: Pervasives.epsilon_float,
                        maxValue: 5.0,
                        scale: /* Linear */0,
                        size: 50
                      },
                      initialParamValue: envelope.envelopeParams.decay,
                      setParamValue: (function (value) {
                          return Envelope$WebAudio.update({
                                      TAG: /* Decay */1,
                                      _0: value
                                    }, envelope);
                        })
                    })), React.createElement("div", undefined, React.createElement(Knob$WebAudio.make, {
                      name: "SUSTAIN",
                      config: {
                        minValue: Pervasives.epsilon_float,
                        maxValue: 1.0,
                        scale: /* Linear */0,
                        size: 50
                      },
                      initialParamValue: envelope.envelopeParams.sustain,
                      setParamValue: (function (value) {
                          return Envelope$WebAudio.update({
                                      TAG: /* Sustain */2,
                                      _0: value
                                    }, envelope);
                        })
                    }), React.createElement(Knob$WebAudio.make, {
                      name: "RELEASE",
                      config: {
                        minValue: Pervasives.epsilon_float,
                        maxValue: 5.0,
                        scale: /* Linear */0,
                        size: 50
                      },
                      initialParamValue: envelope.envelopeParams.release,
                      setParamValue: (function (value) {
                          return Envelope$WebAudio.update({
                                      TAG: /* Release */3,
                                      _0: value
                                    }, envelope);
                        })
                    })));
}

var make = EnvelopeUnit;

export {
  make ,
  
}
/* react Not a pure module */
