// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function sizeInPixels(x) {
  return String(x) + "px";
}

function clamp(value, config) {
  var match = value < config.minValue;
  var value$1 = match ? config.minValue : value;
  var match$1 = value$1 > config.maxValue;
  if (match$1) {
    return config.maxValue;
  } else {
    return value$1;
  }
}

function Knob(Props) {
  var name = Props.name;
  var param = Props.param;
  var config = Props.config;
  var mapValueToDegrees = function (value) {
    var domain = config.maxValue - config.minValue;
    var value$1 = value - config.minValue;
    var match = value$1 === 0.0;
    var degrees;
    if (match) {
      degrees = 0.0;
    } else {
      var match$1 = config.scale;
      degrees = match$1 ? 300.0 / Math.log10(domain) * Math.log10(value$1) : 300.0 / domain * value$1;
    }
    return (degrees + 30.0).toString() + "deg";
  };
  var match = React.useState((function () {
          return param.value;
        }));
  var setValue = match[1];
  var value = match[0];
  var match$1 = React.useState((function () {
          return 0;
        }));
  var setPreviousY = match$1[1];
  var previousY = match$1[0];
  var match$2 = React.useState((function () {
          return 0;
        }));
  var setNextY = match$2[1];
  var nextY = match$2[0];
  React.useEffect((function (param$1) {
          var change = previousY - nextY | 0;
          var match = config.scale;
          var scaledChange = match ? Math.pow(Math.abs(change), Math.log10(value)) : Math.abs(change);
          var match$1 = change > 0;
          var newValue = match$1 ? value + scaledChange : value - scaledChange;
          var clampedValue = clamp(newValue, config);
          param.value = clampedValue;
          Curry._1(setValue, (function (param) {
                  return clampedValue;
                }));
          Curry._1(setPreviousY, (function (param) {
                  return nextY;
                }));
          return ;
        }), /* tuple */[
        value,
        previousY,
        nextY
      ]);
  var handleMouseMove = function ($$event) {
    var clientY = $$event.clientY;
    Curry._1(setNextY, (function (param) {
            return clientY;
          }));
    return /* () */0;
  };
  var handleMouseUp = function (param) {
    document.removeEventListener("mousemove", handleMouseMove);
    return /* () */0;
  };
  var handleMouseDown = function ($$event) {
    var clientY = $$event.clientY;
    Curry._1(setNextY, (function (param) {
            return clientY;
          }));
    Curry._1(setPreviousY, (function (param) {
            return clientY;
          }));
    document.addEventListener("mousemove", handleMouseMove);
    document.addEventListener("mouseup", handleMouseUp, {
          capture: false,
          once: true,
          passive: true
        });
    return /* () */0;
  };
  return React.createElement("div", {
              style: {
                padding: "10px",
                width: String(140) + "px"
              }
            }, React.createElement("div", {
                  style: {
                    backgroundColor: "#839264",
                    display: "flex",
                    height: String(120) + "px",
                    margin: "10px",
                    width: String(120) + "px",
                    borderRadius: String(120) + "px",
                    justifyContent: "center",
                    transform: "rotate(" + (mapValueToDegrees(value) + ")")
                  },
                  onMouseDown: handleMouseDown
                }, React.createElement("div", {
                      style: {
                        borderRight: "10px solid transparent",
                        borderBottom: "10px solid black",
                        borderLeft: "10px solid transparent",
                        height: "0",
                        width: "0"
                      }
                    })), React.createElement("div", {
                  style: {
                    display: "flex",
                    justifyContent: "center"
                  }
                }, name + ": ", String(value | 0)));
}

var size = 120;

var offset = 30.0;

var range = 300.0;

var make = Knob;

export {
  size ,
  sizeInPixels ,
  offset ,
  range ,
  clamp ,
  make ,
  
}
/* react Not a pure module */
