// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as $$Array from "bs-platform/lib/es6/array.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as OscillatorUnit$WebAudio from "./OscillatorUnit.bs.js";

function OscillatorRack(Props) {
  var match = React.useState((function () {
          return /* :: */[
                  1,
                  /* [] */0
                ];
        }));
  var setOscillators = match[1];
  return React.createElement("div", undefined, React.createElement("div", {
                  style: {
                    backgroundColor: "#839264",
                    color: "#FFF3F5",
                    display: "inline-block",
                    margin: "10px 15px",
                    padding: "10px"
                  },
                  onClick: (function (param) {
                      return Curry._1(setOscillators, (function (oscs) {
                                    return /* :: */[
                                            List.hd(oscs) + 1 | 0,
                                            oscs
                                          ];
                                  }));
                    })
                }, "Add Oscillator"), React.createElement("div", undefined, $$Array.of_list(List.map((function (osc) {
                            return React.createElement(OscillatorUnit$WebAudio.make, {
                                        name: "Oscillator " + String(osc),
                                        targetOutput: undefined,
                                        key: String(osc)
                                      });
                          }), match[0]))));
}

var make = OscillatorRack;

export {
  make ,
  
}
/* react Not a pure module */
