// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";

function sizeInPixels(x) {
  return String(x) + "px";
}

function Switch(Props) {
  var toggle = Props.toggle;
  var initialState = Props.initialState;
  var children = Props.children;
  var match = React.useState((function () {
          return initialState;
        }));
  var setIsOn = match[1];
  return React.createElement("div", {
              style: {
                display: "inline-block",
                padding: "10px 20px"
              }
            }, React.createElement("h3", {
                  style: {
                    textAlign: "center"
                  }
                }, children), React.createElement("div", {
                  style: {
                    backgroundColor: "#839264",
                    height: String(20) + "px",
                    margin: "10px 20px",
                    width: String(40) + "px"
                  },
                  onClick: (function (param) {
                      Curry._1(toggle, /* () */0);
                      return Curry._1(setIsOn, (function (state) {
                                    return !state;
                                  }));
                    })
                }, React.createElement("div", {
                      style: {
                        backgroundColor: "#112211",
                        height: String(20) + "px",
                        width: String(20) + "px",
                        transform: "translateX(" + ((
                            match[0] ? String(20) + "px" : "0"
                          ) + ")")
                      }
                    })));
}

var width = 40;

var height = 20;

var make = Switch;

export {
  width ,
  height ,
  sizeInPixels ,
  make ,
  
}
/* react Not a pure module */
