// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";

function sizeInPixels(x) {
  return String(x) + "px";
}

function Switch(Props) {
  var isOn = Props.isOn;
  var children = Props.children;
  return React.createElement("div", {
              style: {
                display: "inline-block",
                padding: "10px 20px"
              }
            }, React.createElement("h3", {
                  style: {
                    textAlign: "center"
                  }
                }, children), React.createElement("div", {
                  style: {
                    backgroundColor: "#839264",
                    height: String(20) + "px",
                    margin: "10px 20px",
                    width: String(40) + "px"
                  }
                }, React.createElement("div", {
                      style: {
                        backgroundColor: "#112211",
                        height: String(20) + "px",
                        width: String(20) + "px",
                        transform: "translateX(" + ((
                            isOn ? String(20) + "px" : "0"
                          ) + ")")
                      }
                    })));
}

var width = 40;

var height = 20;

var make = Switch;

export {
  width ,
  height ,
  sizeInPixels ,
  make ,
  
}
/* react Not a pure module */
