// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Caml_obj from "bs-platform/lib/es6/caml_obj.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";
import * as Switch$WebAudio from "./Components/Switch.bs.js";
import * as Keyboard$WebAudio from "./Components/Keyboard.bs.js";
import * as AudioContext$WebAudio from "./WebAudio/AudioContext.bs.js";
import * as OscillatorUnit$WebAudio from "./Components/OscillatorUnit.bs.js";
import * as AppContextProvider$WebAudio from "./Components/AppContextProvider.bs.js";

function App(Props) {
  var match = React.useState((function () {
          return /* [] */0;
        }));
  var setTriggerTargets = match[1];
  var match$1 = React.useState((function () {
          return ;
        }));
  var setAudioContext = match$1[1];
  var audioContext = match$1[0];
  var addToTriggerTargets = function (envelope) {
    return Curry._1(setTriggerTargets, (function (targets) {
                  return /* :: */[
                          envelope,
                          targets
                        ];
                }));
  };
  var removeFromTriggerTargets = function (envelope) {
    return Curry._1(setTriggerTargets, (function (targets) {
                  return List.filter((function (e) {
                                  return Caml_obj.caml_notequal(e, envelope);
                                }))(targets);
                }));
  };
  var createAudioContext = function (param) {
    return Curry._1(setAudioContext, (function (param) {
                  return Caml_option.some(Curry._1(AudioContext$WebAudio.createAudioContext, /* () */0));
                }));
  };
  return React.createElement(AppContextProvider$WebAudio.make, AppContextProvider$WebAudio.makeProps({
                  audioContext: audioContext,
                  triggerTargets: match[0],
                  addToTriggerTargets: addToTriggerTargets,
                  removeFromTriggerTargets: removeFromTriggerTargets
                }, null, /* () */0), React.createElement("div", {
                  style: {
                    position: "absolute",
                    right: "0",
                    top: "0"
                  }
                }, React.createElement(Switch$WebAudio.make, {
                      toggle: createAudioContext,
                      initialState: false,
                      children: "Power"
                    })), audioContext !== undefined ? React.createElement(React.Fragment, undefined, React.createElement(OscillatorUnit$WebAudio.make, {
                        name: "Oscillator One",
                        targetOutput: undefined
                      }), React.createElement(OscillatorUnit$WebAudio.make, {
                        name: "Oscillator Two",
                        targetOutput: undefined
                      })) : null, React.createElement(Keyboard$WebAudio.make, { }));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
