// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var BiquadFilterNode$WebAudio = require("./WebAudio/BiquadFilterNode.bs.js");

var audioCtx = new AudioContext();

var oscillator = audioCtx.createOscillator();

var biquadFilter = audioCtx.createBiquadFilter();

var gain = audioCtx.createGain();

var real = new Float32Array(3);

var imag = new Float32Array(3);

real[0] = 0.0;

real[1] = 1.0;

real[2] = 0.3;

imag[0] = 0.0;

imag[1] = 0.0;

imag[2] = 0.0;

oscillator.setPeriodicWave(audioCtx.createPeriodicWave(real, imag, {
          disableNormalization: true
        }));

oscillator.connect(biquadFilter);

BiquadFilterNode$WebAudio.setType(biquadFilter, /* Lowpass */0);

biquadFilter.frequency.value = 170.0;

biquadFilter.connect(gain);

gain.connect(audioCtx.destination);

oscillator.start();

setTimeout((function (param) {
        biquadFilter.frequency.value = 320.0;
        var timestamp = audioCtx.getOutputTimestamp();
        oscillator.frequency.value = 240.0;
        oscillator.stop(timestamp.contextTime + 2.0);
        return /* () */0;
      }), 2500);

exports.audioCtx = audioCtx;
exports.oscillator = oscillator;
exports.biquadFilter = biquadFilter;
exports.gain = gain;
exports.real = real;
exports.imag = imag;
/* audioCtx Not a pure module */
