// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, BuckleScript and Reason!");

var audioCtx = new AudioContext();

var oscillator = audioCtx.createOscillator();

var gain = audioCtx.createGain();

oscillator.connect(gain);

gain.connect(audioCtx.destination);

oscillator.start();

exports.audioCtx = audioCtx;
exports.oscillator = oscillator;
exports.gain = gain;
/*  Not a pure module */
