// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ReactDOMRe from "reason-react/src/ReactDOMRe.js";
import * as App$WebAudio from "./App.bs.js";

ReactDOMRe.renderToElementWithId(React.createElement(App$WebAudio.make, { }), "app");

export {
  
}
/*  Not a pure module */
